/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductImport } from './routes/product'
import { Route as ProductPhotoImport } from './routes/product.photo'
import { Route as ProductNameImport } from './routes/product.name'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ProductRoute = ProductImport.update({
  path: '/product',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProductPhotoRoute = ProductPhotoImport.update({
  path: '/photo',
  getParentRoute: () => ProductRoute,
} as any)

const ProductNameRoute = ProductNameImport.update({
  path: '/name',
  getParentRoute: () => ProductRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductImport
      parentRoute: typeof rootRoute
    }
    '/product/name': {
      id: '/product/name'
      path: '/name'
      fullPath: '/product/name'
      preLoaderRoute: typeof ProductNameImport
      parentRoute: typeof ProductImport
    }
    '/product/photo': {
      id: '/product/photo'
      path: '/photo'
      fullPath: '/product/photo'
      preLoaderRoute: typeof ProductPhotoImport
      parentRoute: typeof ProductImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ProductRoute: ProductRoute.addChildren({
    ProductNameRoute,
    ProductPhotoRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/product"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/product": {
      "filePath": "product.tsx",
      "children": [
        "/product/name",
        "/product/photo"
      ]
    },
    "/product/name": {
      "filePath": "product.name.tsx",
      "parent": "/product"
    },
    "/product/photo": {
      "filePath": "product.photo.tsx",
      "parent": "/product"
    }
  }
}
ROUTE_MANIFEST_END */
