/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "KvStore": {
      "type": "sst.cloudflare.Kv"
    }
    "StorageBucket": {
      "type": "sst.cloudflare.Bucket"
    }
    "StripePrice": {
      "id": string
      "lookupKey": string
      "type": "stripe.index/price.Price"
    }
    "StripeProduct": {
      "id": string
      "productId": string
      "type": "stripe.index/product.Product"
    }
    "StripePublic": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhook": {
      "id": string
      "secret": string
      "type": "stripe.index/webhookEndpoint.WebhookEndpoint"
    }
    "WWW": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}
